-- 20260225_fix_milestone_feeling_robust.sql
-- Robust fix for milestone feeling increments

-- 1. Ensure the trigger function is updated with robust checks
CREATE OR REPLACE FUNCTION public.fn_update_conversation_on_message()
RETURNS trigger AS $$
DECLARE
  last_sender uuid;
  current_percent int;
  conv_unlock_state int;
  current_exchanges int;
  inc int;
  new_percent int;
  new_unlock_state int;
BEGIN
  -- Get conversation state including exchanges_count
  SELECT last_sender_id, feeling_percent, unlock_state, exchanges_count
  INTO last_sender, current_percent, conv_unlock_state, current_exchanges
  FROM conversations WHERE id = NEW.conversation_id;

  -- Treat NULL as 0
  current_percent := COALESCE(current_percent, 0);
  conv_unlock_state := COALESCE(conv_unlock_state, 0);
  current_exchanges := COALESCE(current_exchanges, 0);

  IF last_sender IS NULL THEN
      -- First message ever (Opener). Initialize sender, no feeling bump.
      UPDATE public.conversations
      SET last_sender_id = NEW.sender_id,
          updated_at = now()
      WHERE id = NEW.conversation_id;
      
  ELSIF NEW.sender_id <> last_sender THEN
      -- It is an exchange (Reply from different user)
      
      -- PRIORITY 1: Identify Milestone Messages
      -- These are generated by the system and should NEVER increase feeling.
      -- We check by mood and also by a character sequence that might be present.
      IF (NEW.mood IS NOT NULL AND NEW.mood LIKE 'milestone_%') OR (NEW.text LIKE '%|--CONTENT--|%') THEN
          inc := 0;
          
      -- PRIORITY 2: Explicit ZERO delta
      -- If the app explicitly sends 0, respect it.
      ELSIF NEW.feeling_delta = 0 THEN
          inc := 0;
          
      -- PRIORITY 3: First Exchange (Opener)
      -- Opener doesn't increase feeling, it just starts the conversation.
      ELSIF current_exchanges = 0 THEN
          inc := 0;
          
      ELSE
          -- Standard exchange: Default to 5 unless specific delta provided
          inc := COALESCE(NEW.feeling_delta, 5);
      END IF;

      new_percent := LEAST(100, current_percent + inc);
      
      -- Calculate new unlock state
      IF new_percent >= 100 THEN new_unlock_state := 4;
      ELSIF new_percent >= 75 THEN new_unlock_state := 3;
      ELSIF new_percent >= 50 THEN new_unlock_state := 2;
      ELSIF new_percent >= 25 THEN new_unlock_state := 1;
      ELSE new_unlock_state := 0;
      END IF;

      -- Update conversation
      UPDATE public.conversations
      SET exchanges_count = current_exchanges + 1,
          last_sender_id = NEW.sender_id,
          feeling_percent = new_percent,
          unlock_state = GREATEST(conv_unlock_state, new_unlock_state), -- Never downgrade state
          updated_at = now()
      WHERE id = NEW.conversation_id;
  ELSE
      -- Same sender sending again. Just update timestamp.
      UPDATE public.conversations
      SET last_sender_id = NEW.sender_id, -- Keep same
          updated_at = now()
      WHERE id = NEW.conversation_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. Final verification of the trigger itself
-- (Trigger usually exists from previous migrations, but we ensure it's pointing to our function)
DROP TRIGGER IF EXISTS trg_update_conversation_on_message ON public.messages;
CREATE TRIGGER trg_update_conversation_on_message
AFTER INSERT ON public.messages
FOR EACH ROW EXECUTE PROCEDURE public.fn_update_conversation_on_message();
