-- 20260308000000_cap_feeling_for_blocked.sql
-- Cap feeling percent at 75% if an active block exists between the two users

CREATE OR REPLACE FUNCTION public.fn_update_conversation_on_message()
RETURNS trigger AS $$
DECLARE
  last_sender uuid;
  current_percent int;
  conv_unlock_state int;
  current_exchanges int;
  conv_user_a uuid;
  conv_user_b uuid;
  inc int;
  new_percent int;
  new_unlock_state int;
  is_blocked boolean;
BEGIN
  -- Get conversation state including exchanges_count
  SELECT last_sender_id, feeling_percent, unlock_state, exchanges_count, user_a_id, user_b_id
  INTO last_sender, current_percent, conv_unlock_state, current_exchanges, conv_user_a, conv_user_b
  FROM conversations WHERE id = NEW.conversation_id;

  -- Treat NULL as 0
  current_percent := COALESCE(current_percent, 0);
  conv_unlock_state := COALESCE(conv_unlock_state, 0);
  current_exchanges := COALESCE(current_exchanges, 0);

  -- Check block status between the two users
  SELECT EXISTS(
    SELECT 1 FROM user_blocks
    WHERE ((blocker_id = conv_user_a AND blocked_id = conv_user_b) OR
           (blocker_id = conv_user_b AND blocked_id = conv_user_a))
  ) INTO is_blocked;

  IF last_sender IS NULL THEN
      -- First message ever (Opener). Initialize sender, no feeling bump.
      UPDATE public.conversations
      SET last_sender_id = NEW.sender_id,
          updated_at = now()
      WHERE id = NEW.conversation_id;
      
  ELSIF NEW.sender_id <> last_sender THEN
      -- It is an exchange (Reply from different user)
      
      -- PRIORITY 1: Identify Milestone Messages
      -- These are generated by the system and should NEVER increase feeling.
      -- We check by mood and also by a character sequence that might be present.
      IF (NEW.mood IS NOT NULL AND NEW.mood LIKE 'milestone_%') OR (NEW.text LIKE '%|--CONTENT--|%') THEN
          inc := 0;
          
      -- PRIORITY 2: Explicit ZERO delta
      -- If the app explicitly sends 0, respect it.
      ELSIF NEW.feeling_delta = 0 THEN
          inc := 0;
          
      -- PRIORITY 3: First Exchange (Opener)
      -- Opener doesn't increase feeling, it just starts the conversation.
      ELSIF current_exchanges = 0 THEN
          inc := 0;
          
      ELSE
          -- Standard exchange: Default to 5 unless specific delta provided
          inc := COALESCE(NEW.feeling_delta, 5);
      END IF;

      -- Apply cap based on block status
      IF is_blocked THEN
          new_percent := LEAST(75, current_percent + inc);
      ELSE
          new_percent := LEAST(100, current_percent + inc);
      END IF;
      
      -- Calculate new unlock state
      IF new_percent >= 100 THEN new_unlock_state := 4;
      ELSIF new_percent >= 75 THEN new_unlock_state := 3;
      ELSIF new_percent >= 50 THEN new_unlock_state := 2;
      ELSIF new_percent >= 25 THEN new_unlock_state := 1;
      ELSE new_unlock_state := 0;
      END IF;

      -- Update conversation
      UPDATE public.conversations
      SET exchanges_count = current_exchanges + 1,
          last_sender_id = NEW.sender_id,
          feeling_percent = new_percent,
          unlock_state = GREATEST(conv_unlock_state, new_unlock_state), -- Never downgrade state
          updated_at = now()
      WHERE id = NEW.conversation_id;
  ELSE
      -- Same sender sending again. Just update timestamp.
      UPDATE public.conversations
      SET last_sender_id = NEW.sender_id, -- Keep same
          updated_at = now()
      WHERE id = NEW.conversation_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-verify trigger
DROP TRIGGER IF EXISTS trg_update_conversation_on_message ON public.messages;
CREATE TRIGGER trg_update_conversation_on_message
AFTER INSERT ON public.messages
FOR EACH ROW EXECUTE PROCEDURE public.fn_update_conversation_on_message();
